In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
students = [ 
    {"name": "John", "marks": 85, "attendance": 90}, 
    {"name": "Jane", "marks": None, "attendance": 95}, 
    {"name": "Bob", "marks": 110, "attendance": 80}, 
    {"name": "Alice", "marks": 70, "attendance": None}, 
    {"name": "", "marks": 60, "attendance": 85} 
]

In [4]:
pd_students = pd.DataFrame(students)
pd_students

    name  marks  attendance
0   John   85.0        90.0
1   Jane    NaN        95.0
2    Bob  110.0        80.0
3  Alice   70.0         NaN
4          60.0        85.0

In [5]:
pd_students['marks'] = pd_students['marks'].fillna(pd_students['marks'].mean())
pd_students

    name   marks  attendance
0   John   85.00        90.0
1   Jane   81.25        95.0
2    Bob  110.00        80.0
3  Alice   70.00         NaN
4          60.00        85.0

In [6]:
pd_students.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   marks       5 non-null      float64
 2   attendance  4 non-null      float64
dtypes: float64(2), str(1)
memory usage: 252.0 bytes

In [7]:
pd_students = pd_students[pd_students['name'] != '']

In [8]:
pd_students['attendance'] = pd_students['attendance'].fillna(pd_students['attendance'].median())
pd_students

    name   marks  attendance
0   John   85.00        90.0
1   Jane   81.25        95.0
2    Bob  110.00        80.0
3  Alice   70.00        90.0

In [9]:
pd_students = pd_students[pd_students['marks'] <= 100]
pd_students

    name  marks  attendance
0   John  85.00        90.0
1   Jane  81.25        95.0
3  Alice  70.00        90.0

In [10]:
pd_students = pd_students[pd_students['name'] != '']

In [11]:
pd_students

    name  marks  attendance
0   John  85.00        90.0
1   Jane  81.25        95.0
3  Alice  70.00        90.0

In [12]:
pd_students['grade'] = pd_students['marks'].apply(lambda x: 'A' if x >= 80 else ('B' if x >= 60 else 'C'))
pd_students

    name  marks  attendance grade
0   John  85.00        90.0     A
1   Jane  81.25        95.0     A
3  Alice  70.00        90.0     B

In [13]:

pd_students.to_json('Cleaned_Data.json')

In [14]:
data = pd.read_json('Cleaned_Data.json')
print(data)

    name  marks  attendance grade
0   John  85.00          90     A
1   Jane  81.25          95     A
3  Alice  70.00          90     B

In [15]:
avg_marks = pd_students['marks'].mean()
toper = pd_students[pd_students['marks'] == pd_students['marks'].max()]['name'].values[0]
print(f"Average: {avg_marks}")
print(f"Topper: {toper}")

Average: 78.75
Topper: John

In [16]:
print("Grade Distribution:")
grade_counts = pd_students['grade'].value_counts()
print(grade_counts)

Grade Distribution:
grade
A    2
B    1
Name: count, dtype: int64

In [29]:
print("Cleaned Data:\n",data)

print("\nAverage Marks:", avg_marks)

print("\nTopper:", toper)

print("\nGrade Distribution:")
for grade, count in grade_counts.items():
    print(f"{grade}: {count}")

Cleaned Data:
     name  marks  attendance grade
0   John  85.00          90     A
1   Jane  81.25          95     A
3  Alice  70.00          90     B

Average Marks: 78.75

Topper: John

Grade Distribution:
A: 2
B: 1