In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df  = pd.read_csv('logs.csv')
df
df1 = df

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      6 non-null      str
 1   log_level      6 non-null      str
 2   response_time  5 non-null      str
dtypes: str(3)
memory usage: 276.0 bytes

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      6 non-null      str
 1   log_level      6 non-null      str
 2   response_time  5 non-null      str
dtypes: str(3)
memory usage: 276.0 bytes

In [5]:
df = df.dropna()
df = df[df['response_time'] !='abc ']
df['response_time'] = df['response_time'].astype(int)
df

  timestamp log_level  response_time
0     10:00      INFO            120
1     10:01     ERROR            300
3     10:03   WARNING            250
5     10:05      INFO            100

In [6]:
# remove 
log_levels = df['log_level'].value_counts()
print(log_levels)

log_level
INFO       2
ERROR      1
WARNING    1
Name: count, dtype: int64

In [7]:
def catagory(df):
    if df["response_time"] < 150:
        return "FAST"
    elif df["response_time"] <= 300:
        return "MEDIUM"    
    else:
        return "SLOW"
df["category"] = df.apply(catagory, axis=1)
df

  timestamp log_level  response_time category
0     10:00      INFO            120     FAST
1     10:01     ERROR            300   MEDIUM
3     10:03   WARNING            250   MEDIUM
5     10:05      INFO            100     FAST

In [8]:
average_response_time = df['response_time'].mean()
no_slow_responses = df[df['category'] == 'SLOW'].shape[0]

In [9]:
'''ERROR LOGS: 
10:02 → Invalid response_time 
10:04 → Missing response_time'''
def erlog(df1):
    if df1["response_time"] == 'abc ':
        return "Invalid response_time"
    elif pd.isna(df1["response_time"]):
        return "Missing response_time"
    else:
        return "No error"

In [10]:
df1
df1["error_log"] = df1.apply(erlog, axis=1)
df1

  timestamp log_level response_time              error_log
0     10:00      INFO          120                No error
1     10:01     ERROR          300                No error
2     10:02      INFO          abc   Invalid response_time
3     10:03   WARNING          250                No error
4     10:04     ERROR           NaN  Missing response_time
5     10:05      INFO          100                No error

In [14]:
print("LOG LEVEL COUNT: ")
for log_level, count in log_levels.items():
    print(f"{log_level}: {count}")
print()
print("AVERAGE RESPONSE TIME: " , average_response_time)
print()
print("SLOW REQUEST:", no_slow_responses)
print()
print("ERROR LOGS: ")
for index, row in df1.iterrows():
    if row["error_log"] != "No error":
        print(f"{row['timestamp']} → {row['error_log']}")

LOG LEVEL COUNT:
INFO: 2
ERROR: 1
WARNING: 1

AVERAGE RESPONSE TIME:  192.5

SLOW REQUEST: 0

ERROR LOGS:
10:02 → Invalid response_time
10:04 → Missing response_time