### 1. Supervised vs Unsupervised Learning
#### 1. Should this problem use supervised or unsupervised learning?


This problem should use Unsupervised Learning.

#### 2. Which algorithm would you use?


K-Means Clustering

#### 3. Explanation


There is no target variable or label in the dataset. The goal is to group similar customers together based on features like age, income, purchase frequency, and total spending. Therefore clustering algorithms such as K-Means are appropriate.

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans

In [3]:
df  = pd.read_excel('q1.xlsx')
df.head()

   CustomerID  Age  Income  Purchase_Frequency  Total_Spend
0           1   25   30000                   5          200
1           2   40   80000                  15         1200
2           3   35   50000                  10          600
3           4   23   28000                   4          180

In [4]:
x = df[[ "Age",  "Income","Purchase_Frequency","Total_Spend"]]
kmeans = KMeans(n_clusters=3, random_state=0)
kmeans.fit(x)
df['Cluster'] = kmeans.labels_
df.head()

   CustomerID  Age  Income  Purchase_Frequency  Total_Spend  Cluster
0           1   25   30000                   5          200        2
1           2   40   80000                  15         1200        1
2           3   35   50000                  10          600        0
3           4   23   28000                   4          180        2

In [5]:
print(df[['CustomerID', 'Cluster']])

   CustomerID  Cluster
0           1        2
1           2        1
2           3        0
3           4        2

### 2. Supervised Learning – Prediction Problem

#### 1. Type of ML problem

This is a Supervised Learning problem and specifically a Classification problem because the output is Yes or No.

#### 2. Algorithms that can be used

- Logistic Regression

- Decision Tree

- Random Forest

- Support Vector Machine

#### 3. Target Variable

The target variable is Default (Yes / No).

The model learns from labeled data to predict whether a new customer will default on a loan.

In [17]:
df2 = pd.read_excel('q2.xlsx')
df2.head()

   CustomerID  Income  CreditScore  LoanAmount Default
0           1   50000          700       20000      No
1           2   30000          600       25000     Yes
2           3   80000          750       15000      No
3           4   25000          580       30000     Yes

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
df2["Default"] = df2["Default"].map({"Yes": True, "No": False})

In [20]:
df2.head()

   CustomerID  Income  CreditScore  LoanAmount  Default
0           1   50000          700       20000    False
1           2   30000          600       25000     True
2           3   80000          750       15000    False
3           4   25000          580       30000     True

In [29]:
model = LinearRegression() 
X = df2[['Income', 'CreditScore', 'LoanAmount']]
y = df2['Default']
model.fit(X, y)
a = int(input("Enter Income: "))
b = int(input("Enter Credit Score: "))
c = int(input("Enter Loan Amount: "))
new_customer = np.array([[a,b,c]]) 
prediction = model.predict(new_customer)
#pridict yes or no
if prediction[0] >= 0.5:
    Default = "Yes"
else:
    Default = "No"
print(f"Predicted Default: {Default}")

Predicted Default: Yes

c:\Users\indiranivas_s\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

### 3. Overfitting Scenario

#### 1. What problem is the model facing?

The model is facing Overfitting.

#### 2. Why is this happening?

Reasons:

- The model memorizes training data instead of learning patterns.

- The model is too complex.

- The dataset is too small.

#### 3. Three solutions

- Use Cross Validation

- Apply Regularization (L1 / L2)

- Reduce model complexity

- Increase training data

In [30]:
df3 = pd.read_excel('q3.xlsx')
df3.head()

   HouseSize  Bedrooms   Price
0       1000         2  200000
1       1200         3  250000
2       1500         3  300000

In [43]:

from sklearn.linear_model import Ridge
model = Ridge(alpha=1.0)

In [41]:

X = df3[['HouseSize', 'Bedrooms']]
y = df3['Price']
model.fit(X, y)
new_house = np.array([[2000, 3]])
predicted_price = model.predict(new_house)
print(f"Predicted Price: {predicted_price[0]}")

Predicted Price: 397870.8737141094

c:\Users\indiranivas_s\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

### 4. Underfitting Scenario

#### 1. What is the issue?

The model is suffering from Underfitting.

#### 2. Why is it happening?

Reasons:

 - The model is too simple to capture patterns.

 - Only one feature (advertising budget) is used.

 - The relationship may be non-linear.

#### 3. How can it be improved?

 - Use a more complex model

 - Add more features

 - Use Polynomial Regression

 - Increase dataset size

In [45]:
d4 = pd.read_csv('q4.csv')
d4.head()

   Advertising_Budget  TV_Ads  Social_Media_Ads  Radio_Ads  Sales
0                1660     837               520        212  32987
1                5991    3051              1404        636  98321
2                4572    1998               967        862  81120
3                3892    2312               948        785  70723
4                1266     703               284        130  34883

In [50]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error
model = LinearRegression()

In [52]:
x = d4[['Advertising_Budget', 'TV_Ads', 'Social_Media_Ads', 'Radio_Ads']]
y = d4['Sales']
poly = PolynomialFeatures(degree=2, include_bias=False)
x_poly = poly.fit_transform(x)
model.fit(x_poly, y)
new_campaign = np.array([[1500, 800, 400, 200]])
new_campaign_poly = poly.transform(new_campaign)
predicted_sales = model.predict(new_campaign_poly)
print(f"Predicted Sales: {predicted_sales[0]}")

Predicted Sales: 29408.43963663351

c:\Users\indiranivas_s\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(

### 5. Train-Test Split

#### 1. How will you split the dataset?

For 10,000 records:

- Training Data = 80% = 8000

- Testing Data = 20% = 2000

#### 2. Why should we not train on the entire dataset?

If we train on the entire dataset:

- The model cannot be evaluated properly

- We cannot test generalization ability

- It may lead to overfitting

Testing data helps measure real-world performance.

In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd


data = {'Feature':[i for i in range(10000)],
        'Target':[i%2 for i in range(10000)]}

df = pd.DataFrame(data)

X = df[['Feature']]
y = df['Target']

8000
2000

In [54]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

print(len(X_train))
print(len(X_test))

8000
2000

### 6. Cross Validation

#### 1. Why is accuracy unstable?

Accuracy changes because of:

- Different train-test splits

- Small dataset

- Random sampling variations

#### 2. What technique can solve this?

K-Fold Cross Validation

#### 3. Explanation of K-Fold Cross Validation

In K-Fold Cross Validation:

- Dataset is divided into K equal parts (folds).

- Model is trained K times.

- Each fold becomes the testing set once.

- Remaining folds are used for training.

- Final accuracy is the average of all runs.

In [59]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import numpy as np

In [58]:
X = np.random.rand(1000,3)
y = np.random.randint(0,2,1000)

In [60]:
model = LogisticRegression()
scores = cross_val_score(model,X,y,cv=5)
print("Fold Accuracy:",scores)
print("Average Accuracy:",scores.mean())

Fold Accuracy: [0.48  0.515 0.5   0.525 0.535]
Average Accuracy: 0.511

### 7. ML Pipeline

#### 1. Why should we use a pipeline?

Benefits of a Pipeline:

- Automates data preprocessing + model training

- Prevents data leakage

- Keeps workflow organized and reproducible

- Reduces coding errors

In [61]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [62]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])

In [63]:
pipeline.fit(X_train,y_train)

prediction = pipeline.predict(X_test)

print(prediction)

[0.50157721 0.50068961 0.49901799 ... 0.50248349 0.49865797 0.50196044]

### 8. Bias-Variance Tradeoff

#### 1. Which model has high variance?

Model A

Training Accuracy = 95%
Testing Accuracy = 60%

This indicates overfitting (high variance).

#### 2. Which model is better?

Model B

Training Accuracy = 75%
Testing Accuracy = 73%

Because it generalizes better to unseen data.

#### 3. Bias vs Variance

Bias

- Error due to oversimplified model

- Leads to underfitting

Example: Linear model for complex data

Variance

- Error due to overly complex model

- Model learns noise in training data

Example: Deep tree memorizing training data

In [65]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

linear = LinearRegression()

tree = DecisionTreeRegressor()

linear.fit(X_train,y_train)
tree.fit(X_train,y_train)

print("Models trained")
print("Linear Regression Coefficients:", linear.coef_)
print("Decision Tree Feature Importances:", tree.feature_importances_)

Models trained
Linear Regression Coefficients: [5.66072815e-07]
Decision Tree Feature Importances: [1.]